---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: a == 0
  checked: true
- value: a == null
  checked: false
- value: b == true
  checked: false
- value: b == false
  checked: true
- value: c == null
  checked: true
- value: c == ""
  checked: false
- value: d == ""
  checked: false
- value: d == "hola"
  checked: true
